development = true

[webserver]
host = "0.0.0.0"
port = 44444

[prism]
host = "127.0.0.1"
port = 55555
signing_key = "~/.prism/PrismMessengerServer_SigningKey.p8"

[apns]
team_id = "T1E234A5M"
key_id = "K12E34Y56"
private_key = "~/.prism/AuthKey_K12E34Y56.p8"
bundle_id = "com.whatever.PrismMessenger"

[database]
type = "sqlite"
path = "~/.prism/prism_messenger.sqlite"

[telemetry.metrics]
enabled = true
endpoint = "https://alloy.prism.boo"

[telemetry.metrics.auth]
enabled = true
username = "username"
password = "password"

[telemetry.logs]
enabled = true
endpoint = "https://alloy.prism.boo"

[telemetry.logs.auth]
enabled = true
username = "username"
password = "password"

[telemetry.traces]
enabled = false
endpoint = "https://alloy.prism.boo"

[telemetry.traces.auth]
enabled = false
username = ""
password = ""

[telemetry.profiles]
enabled = false
endpoint = "https://alloy.prism.boo"

[telemetry.profiles.auth]
enabled = false
username = ""
password = ""

[telemetry.global_labels.labels]
node_name = "prism-messenger-server-0"
