development = true

[webserver]
host = "0.0.0.0"
port = 44444

[prism]
host = "127.0.0.1"
port = 55555
signing_key_path = "~/.prism/PrismMessengerServer_SigningKey.p8"

[apns]
team_id = "T1E234A5M"
key_id = "K12E34Y56"
private_key_path = "~/.prism/AuthKey_K12E34Y56.p8"
bundle_id = "com.whatever.PrismMessenger"

[database]
type = "sqlite"
path = "~/.prism/prism_messenger.sqlite"
